/** 知识库第3批 — 补全到各 ~100 种 */
import fs from 'fs'
import path from 'path'

const BASE = path.resolve(process.cwd(), 'data', 'knowledge', 'species')
const catMap: Record<string, string> = {
  '消化系统':'digestive','泌尿系统':'urinary','呼吸系统':'respiratory','心血管':'cardiovascular',
  '皮肤科':'dermatology','传染病':'infectious','寄生虫':'parasitic','内分泌':'endocrine',
  '骨骼肌肉':'musculoskeletal','产科':'reproductive','中毒':'emergency_toxicology',
  '眼科':'ophthalmology','耳科':'otology','口腔':'dental','神经系统':'nervous','血液':'hematology','免疫':'immune',
}

interface D { id:string;disease:string;species:string[];category:string;primary:string[];secondary:string[];urgency:string;diagnosis:string;homeCare:string[];forbidden:string[];differential:{disease:string;differentiator:string;questions:string[]}[] }
function e(d:D){return{id:d.id,disease:d.disease,species:d.species,category:d.category,symptoms:{primary:d.primary,secondary:d.secondary,detail:{}},urgency:d.urgency,diagnosis_basis:d.diagnosis,home_care:d.homeCare.join('\n'),forbidden_care:d.forbidden.map(f=>({rule:f,condition:'default'})),medication:['需兽医处方'],vet_threshold:'症状加重或急症请立即就医',confidence:'high',differential_diagnosis:d.differential.map(dd=>({disease:dd.disease,differentiator:dd.differentiator,key_questions:dd.questions})),references:['小动物医学参考'],version:1,status:'active',created_at:'2026-06-14',updated_at:'2026-06-14',reviewed_by:null}}

const DOG3: D[] = [
  {id:'canine-dig-009',disease:'胃溃疡',species:['犬'],category:'消化系统',primary:['呕吐（可能带血/咖啡渣样）','黑便（柏油样）','上腹痛'],secondary:['食欲下降','体重下降','贫血'],urgency:'high',diagnosis:'胃溃疡是胃黏膜糜烂至黏膜下层，常见病因：NSAIDs使用、应激、肥大细胞瘤（高胃泌素血症）、肝病。胃镜+活检可确诊。',homeCare:['停用NSAIDs','胃黏膜保护剂（硫糖铝）','抑酸药（奥美拉唑/法莫替丁）','易消化食物'],forbidden:['禁止继续使用NSAIDs','禁止喂食刺激性食物'],differential:[{disease:'胃肿瘤',differentiator:'肿瘤内镜见肿块，活检可确诊；溃疡为凹陷性病变',questions:['有无做过胃镜？']}]},
  {id:'canine-dig-010',disease:'蛋白丢失性肠病(PLE)',species:['犬'],category:'消化系统',primary:['慢性腹泻','体重显著下降','腹水'],secondary:['呕吐','下肢水肿','嗜睡'],urgency:'high',diagnosis:'PLE是肠道蛋白质丢失过多导致低蛋白血症。约克夏/罗威纳/软毛麦色梗等品种高发。常见病因为IBD和肠淋巴管扩张。血液低白蛋白+粪便α1-蛋白酶抑制剂升高可诊断。',homeCare:['超低脂饮食（淋巴管扩张）','激素/免疫抑制剂（IBD）','补充白蛋白（严重者）','维生素补充（脂溶性维生素）'],forbidden:['禁止高脂饮食（淋巴管扩张犬）','禁止不监测白蛋白'],differential:[{disease:'肝衰竭',differentiator:'肝衰竭白蛋白+凝血因子同时下降，肝功能指标显著升高',questions:['肝功能指标如何？']}]},
  {id:'canine-resp-006',disease:'过敏性支气管炎',species:['犬'],category:'呼吸系统',primary:['慢性咳嗽（干咳）','运动不耐受'],secondary:['偶尔喘息','呼吸困难（严重者）'],urgency:'medium',diagnosis:'过敏性支气管炎是对吸入性过敏原（花粉/尘螨/霉菌）的过敏性气道炎症。排除其他咳嗽病因后诊断。支气管灌洗见嗜酸性粒细胞增多支持诊断。',homeCare:['环境过敏原控制（空气净化器）','避免烟雾/香薰','激素吸入剂（遵医嘱）','支气管扩张剂'],forbidden:['禁止在犬周围吸烟','禁止使用有强烈气味的清洁剂'],differential:[{disease:'气管塌陷',differentiator:'气管塌陷X光可见气管管径变化，咳嗽有特征性鹅鸣音',questions:['咳嗽声音怎样？X光有无气管塌陷？']}]},
  {id:'canine-resp-007',disease:'吸入性肺炎',species:['犬'],category:'呼吸系统',primary:['呼吸困难','发热','咳嗽（湿咳）'],secondary:['精神萎靡','食欲废绝','发绀'],urgency:'critical',diagnosis:'吸入性肺炎是异物（呕吐物/食物/液体）吸入肺内导致感染和炎症。常见于麻醉后/巨食道症/喉麻痹/癫痫发作后犬。X光+支气管灌洗可确诊。',homeCare:['⚠️ 需住院治疗','广谱抗生素','氧气疗法','静脉输液','治疗原发病因（巨食道症/喉麻痹）'],forbidden:['禁止对高风险犬不做预防（麻醉前禁食/贝利椅喂食）'],differential:[{disease:'细菌性肺炎',differentiator:'社区获得性肺炎有咳嗽发热但无吸入病史',questions:['有无麻醉/呕吐/癫痫发作后发生？']}]},
  {id:'canine-resp-008',disease:'胸腔积液',species:['犬'],category:'呼吸系统',primary:['呼吸困难','坐姿呼吸','呼吸急促'],secondary:['咳嗽','发绀','心音遥远'],urgency:'critical',diagnosis:'胸腔积液是胸膜腔内液体积聚（漏出液/渗出液/乳糜/血液）。病因包括心衰、肿瘤、感染（脓胸）、外伤、低蛋白血症。胸腔穿刺+积液分析+X光/B超可确诊。',homeCare:['⚠️ 立即就医','胸腔穿刺引流','治疗原发病','严重者胸腔引流管留置'],forbidden:['禁止不查找原发病因就反复穿刺'],differential:[{disease:'肺水肿',differentiator:'肺水肿X光见肺间质/肺泡浸润，胸腔积液见肋膈角消失',questions:['X光有无胸腔积液影像？']}]},
  {id:'canine-cardio-004',disease:'肺动脉高压',species:['犬'],category:'心血管',primary:['运动不耐受','呼吸困难','昏厥'],secondary:['右心衰竭体征（腹水/颈静脉怒张）','发绀'],urgency:'high',diagnosis:'肺动脉高压是肺动脉压力持续升高导致右心室负荷增加。可继发于心丝虫病/慢性肺病/左心衰。心脏B超（三尖瓣反流速度推算肺动脉压）可诊断。',homeCare:['治疗原发病（心丝虫/肺病）','西地那非（扩张肺动脉）','控制运动','吸氧（急性加重期）'],forbidden:['禁止剧烈运动','禁止不治疗原发病'],differential:[{disease:'原发性右心衰竭',differentiator:'B超测肺动脉压可区分；原发性右心衰肺动脉压不高',questions:['有无心丝虫检测？B超肺动脉压多少？']}]},
  {id:'canine-cardio-005',disease:'心包积液',species:['犬'],category:'心血管',primary:['嗜睡','腹围增大（腹水）','运动不耐受'],secondary:['呼吸困难','心音遥远','奇脉'],urgency:'critical',diagnosis:'心包积液是心包腔内液体积聚→心脏压塞。常见病因：肿瘤（血管肉瘤/心脏基瘤）、特发性心包炎。B超（心包腔内无回声区+右心房舒张期塌陷）可确诊。心包穿刺可挽救生命。',homeCare:['⚠️ 立即就医','心包穿刺引流','查找原发病因（B超排查肿瘤）','心包切除术（复发者）'],forbidden:['禁止等待观察（心脏压塞可迅速致死）'],differential:[{disease:'扩张型心肌病',differentiator:'DCM以心脏扩大+收缩功能下降为特征，无心包积液',questions:['B超有无心包积液？']}]},
  {id:'canine-neuro-004',disease:'退行性脊髓病(DM)',species:['犬'],category:'神经系统',primary:['后肢渐进性无力','共济失调','拖拽后肢'],secondary:['肌肉萎缩','大小便失禁（晚期）'],urgency:'medium',diagnosis:'DM是老年大型犬（德牧/拳师/柯基）的渐进性脊髓退行性疾病。类似人ALS。诊断依靠排除其他病因（IVDD/肿瘤/关节炎）+MRI。无有效治疗，病程数月至数年。',homeCare:['物理治疗维持肌力','辅助行走工具（轮椅）','防褥疮护理','保持生活质量'],forbidden:['禁止不排除可治疗病因（IVDD/肿瘤）就诊断DM'],differential:[{disease:'IVDD',differentiator:'IVDD有疼痛+MRI可见椎间盘压迫，DM无疼痛无压迫',questions:['有无疼痛表现？MRI有无脊髓压迫？']}]},
  {id:'canine-neuro-005',disease:'肝性脑病',species:['犬'],category:'神经系统',primary:['行为改变','共济失调','流涎'],secondary:['昏睡','抽搐','定向力障碍'],urgency:'critical',diagnosis:'肝性脑病是肝功能严重受损或门体分流(PSS)导致血氨升高→脑神经毒性。进食高蛋白后症状加重。血氨升高+肝功能异常+PSS造影可诊断。',homeCare:['低蛋白饮食','乳果糖（降低肠道氨吸收）','抗生素（减少肠道产氨菌）','手术结扎PSS分流血管'],forbidden:['禁止高蛋白饮食','禁止不治疗（持续高氨可致永久性脑损伤）'],differential:[{disease:'原发性癫痫',differentiator:'癫痫发作与进食无关，血氨正常；肝性脑病进食后加重',questions:['症状是否在进食后加重？血氨多少？']}]},
  {id:'canine-derm-008',disease:'皮肤真菌病',species:['犬'],category:'皮肤科',primary:['圆形脱毛斑','皮屑','红斑'],secondary:['瘙痒（轻中度）','甲沟炎'],urgency:'medium',diagnosis:'犬皮肤真菌病多为Microsporum canis/gypseum或Trichophyton感染。幼犬和免疫低下犬高发。Wood灯（部分菌株荧光）+真菌培养+毛发镜检可确诊。人畜共患。',homeCare:['抗真菌药浴（咪康唑/恩康唑）','口服抗真菌药（伊曲康唑/特比萘芬）','环境彻底消毒','治疗至连续2次培养阴性'],forbidden:['禁止自行停药','禁止不处理环境','注意人感染风险'],differential:[{disease:'蠕形螨病',differentiator:'蠕形螨深部刮片见虫体；癣菌脱毛边界清晰呈圆形',questions:['脱毛斑是圆形吗？皮肤刮片结果？']}]},
  {id:'canine-derm-009',disease:'锌反应性皮炎',species:['犬'],category:'皮肤科',primary:['口周/眼周/耳廓脱屑和结痂','皮肤增厚'],secondary:['脱毛','继发感染'],urgency:'medium',diagnosis:'锌反应性皮炎分为I型（饮食锌缺乏，多见于吃廉价粮的幼犬）和II型（遗传性锌吸收障碍，西伯利亚哈士奇/阿拉斯加雪橇犬高发）。补锌后症状改善可诊断。',homeCare:['补充锌制剂（遵医嘱，过量有毒）','改喂高质量犬粮','皮肤局部护理'],forbidden:['禁止自行超量补锌（锌中毒）','禁止不排查其他皮肤病就诊断'],differential:[{disease:'其他角化异常病',differentiator:'补锌诊断性治疗：锌反应性皮炎补锌2-4周后显著改善',questions:['犬品种？补锌后有无改善？']}]},

  // 血液病
  {id:'canine-hema-001',disease:'免疫介导性溶血性贫血(IMHA)',species:['犬'],category:'血液',primary:['牙龈苍白','虚弱','呼吸急促'],secondary:['黄疸','血红蛋白尿','发热'],urgency:'critical',diagnosis:'IMHA是免疫系统攻击自身红细胞导致溶血。可卡犬/贵宾/爱尔兰雪达犬高发。库姆斯试验阳性+球形红细胞增多+血涂片可诊断。需排查潜在诱因（感染/肿瘤/药物/疫苗）。',homeCare:['⚠️ 立即就医','免疫抑制治疗（泼尼松龙+硫唑嘌呤/环孢素）','严重贫血需输血','抗血栓（血栓风险高）'],forbidden:['禁止不排查潜在诱因','禁止自行停药（复发风险）'],differential:[{disease:'巴贝斯虫病',differentiator:'巴贝斯虫血涂片可见红细胞内虫体；IMHA库姆斯试验阳性',questions:['有无蜱虫叮咬史？库姆斯试验结果？']}]},
  {id:'canine-hema-002',disease:'免疫介导性血小板减少症(ITP)',species:['犬'],category:'血液',primary:['皮肤瘀斑/出血点','鼻出血','牙龈出血'],secondary:['黑便','血尿','贫血（严重者）'],urgency:'critical',diagnosis:'ITP是免疫系统破坏血小板导致血小板计数极度下降（<30×10⁹/L）。需排查潜在诱因（感染/药物/肿瘤/疫苗）。',homeCare:['⚠️ 需就医','免疫抑制治疗','严重者输注血小板','避免任何可能导致出血的操作'],forbidden:['禁止进行任何有创操作（抽血/手术）','禁止使用影响血小板的药物（NSAIDs/某些抗生素）'],differential:[{disease:'DIC',differentiator:'DIC血小板+凝血因子同时消耗，PT/APTT延长；ITP仅血小板减少',questions:['有无凝血功能异常？']}]},
  {id:'canine-hema-003',disease:'弥散性血管内凝血(DIC)',species:['犬'],category:'血液',primary:['全身性出血','瘀斑','静脉穿刺处持续渗血'],secondary:['器官功能衰竭','休克'],urgency:'critical',diagnosis:'DIC是严重全身性疾病（败血症/中暑/肿瘤/胰腺炎/蛇咬伤）导致的凝血系统广泛激活和消耗。血小板下降+PT/APTT延长+D二聚体升高+FDP升高可诊断。',homeCare:['⚠️ 此为致命急症，需ICU治疗','治疗原发病（根本）','输注新鲜冰冻血浆/血小板','抗凝治疗（争议，需兽医判断）'],forbidden:['禁止不治疗原发病','禁止常规手术/操作'],differential:[{disease:'ITP',differentiator:'ITP仅血小板减少，凝血功能正常；DIC全凝血系统异常',questions:['PT/APTT有无延长？原发病是什么？']}]},
  {id:'canine-neuro-006',disease:'脑肿瘤',species:['犬'],category:'神经系统',primary:['抽搐（新发作，尤其是>5岁犬）','行为改变','转圈/头倾斜'],secondary:['视力丧失','共济失调','食欲改变'],urgency:'critical',diagnosis:'犬脑肿瘤常见类型：脑膜瘤（可手术）、胶质瘤、垂体瘤。短头品种（拳师/波士顿梗）脑肿瘤风险高。MRI+脑脊液分析可确诊。',homeCare:['MRI确诊','神经外科手术（脑膜瘤可切除）','放射治疗','对症：抗癫痫+激素减轻脑水肿'],forbidden:['禁止不对新发抽搐做MRI排查脑肿瘤'],differential:[{disease:'特发性癫痫',differentiator:'特发性癫痫通常1-5岁首发，MRI正常；脑肿瘤>5岁+MRI见占位',questions:['犬年龄？MRI是否做过？']}]},
  {id:'canine-infect-007',disease:'莱姆病',species:['犬'],category:'传染病',primary:['跛行（游走性）','关节肿胀','发热'],secondary:['精神萎靡','食欲下降','淋巴结肿大'],urgency:'high',diagnosis:'莱姆病由伯氏疏螺旋体经蜱虫叮咬传播。大部分感染犬无症状，少数出现跛行和多关节炎。C6抗体检测+SNAP 4Dx可诊断。',homeCare:['多西环素治疗（4周）','控制疼痛','定期体外驱虫（防蜱）'],forbidden:['禁止不防蜱','禁止不完成全程抗生素'],differential:[{disease:'免疫介导性多关节炎',differentiator:'IMPA无蜱虫接触史、莱姆病抗体阴性、关节液无菌性炎症',questions:['有无蜱虫叮咬史？莱姆病抗体检测？']}]},
  {id:'canine-infect-008',disease:'破伤风',species:['犬'],category:'传染病',primary:['全身肌肉僵硬（第三眼睑脱出）','步态僵硬','痉笑面容'],secondary:['呼吸困难','吞咽困难','对声音/触摸高度敏感'],urgency:'critical',diagnosis:'破伤风由破伤风梭菌经深部伤口感染产生神经毒素。犬对破伤风毒素相对抵抗。特征性表现：第三眼睑脱出+全身僵硬+痉笑（嘴唇后拉）。临床诊断为主。',homeCare:['⚠️ 需住院治疗','伤口清创','抗毒素+抗生素（甲硝唑）','肌肉松弛剂','暗室安静环境护理'],forbidden:['禁止强光/噪音刺激（触发肌肉痉挛）'],differential:[{disease:'士的宁中毒',differentiator:'士的宁中毒有接触史、突发全身抽搐后松弛；破伤风为持续性僵硬',questions:['有无深部伤口？']}]},
  {id:'canine-uro-006',disease:'蛋白尿性肾病',species:['犬'],category:'泌尿系统',primary:['蛋白尿','腹水/水肿（低白蛋白）','体重下降'],secondary:['嗜睡','高血压'],urgency:'high',diagnosis:'蛋白尿性肾病是肾小球疾病导致蛋白质大量丢失。可为免疫介导性（肾小球肾炎）、遗传性（某些品种）、或继发于感染/肿瘤。UPC>2.0+肾活检可确诊。',homeCare:['肾脏处方粮','ACEI减少蛋白尿','抗血栓（血栓风险高）','控制高血压','免疫抑制治疗（免疫介导性）'],forbidden:['禁止高蛋白饮食','禁止不监测血压和UPC'],differential:[{disease:'肾小管疾病',differentiator:'肾小管疾病以糖尿/氨基酸尿为主，肾小球疾病以白蛋白尿为主',questions:['UPC多少？尿蛋白电泳结果？']}]},
]

const CAT3: D[] = [
  {id:'feline-resp-003',disease:'猫肺炎',species:['猫'],category:'呼吸系统',primary:['呼吸困难','咳嗽','发热'],secondary:['食欲废绝','精神萎靡','张口呼吸'],urgency:'critical',diagnosis:'猫肺炎可为细菌性/病毒性/吸入性/真菌性。猫肺炎症状隐匿，常在应激后急性恶化。X光+支气管灌洗+PCR可诊断。',homeCare:['住院治疗','广谱抗生素','氧气疗法','营养支持（可能需饲管）'],forbidden:['禁止不积极治疗（猫肺炎恶化快）'],differential:[{disease:'肺水肿',differentiator:'肺水肿发病更急，X光特征不同，常有心衰病史',questions:['X光表现如何？']}]},
  {id:'feline-resp-004',disease:'猫支气管炎',species:['猫'],category:'呼吸系统',primary:['慢性咳嗽','呼吸音粗','偶发呼吸困难'],secondary:['食欲下降','精神萎靡'],urgency:'medium',diagnosis:'猫支气管炎是支气管慢性炎症，可能与过敏/刺激物/感染相关。咳嗽可能是猫唯一症状。X光见支气管壁增厚+支气管灌洗细胞学可诊断。',homeCare:['环境控制（无尘猫砂/空气净化器）','支气管扩张剂+激素（吸入或口服）','控制应激'],forbidden:['禁止在猫周围吸烟','禁止使用有尘猫砂'],differential:[{disease:'猫哮喘',differentiator:'哮喘急性发作症状更剧烈（伸颈呼吸/喘鸣），支气管灌洗见嗜酸性粒细胞',questions:['发作时有无喘鸣音？']}]},
  {id:'feline-resp-005',disease:'猫脓胸',species:['猫'],category:'呼吸系统',primary:['呼吸困难','发热','精神萎靡'],secondary:['食欲废绝','体重下降','心音遥远'],urgency:'critical',diagnosis:'猫脓胸是胸腔内化脓性积液。常见于多猫环境幼猫，常继发于呼吸道感染。胸腔穿刺抽出脓性积液可确诊。需胸腔引流+抗生素灌洗。',homeCare:['⚠️ 需住院治疗','胸腔引流管留置+灌洗','广谱抗生素（长疗程）','营养支持'],forbidden:['禁止仅用抗生素不引流脓液'],differential:[{disease:'乳糜胸',differentiator:'乳糜胸积液为乳白色（乳糜），甘油三酯高；脓胸为脓性',questions:['积液外观和细胞学检查？']}]},
  {id:'feline-cardio-003',disease:'猫心肌病(限制型)',species:['猫'],category:'心血管',primary:['呼吸急促','运动不耐受','嗜睡'],secondary:['血栓栓塞症状（后肢瘫痪）','腹水'],urgency:'high',diagnosis:'限制型心肌病(RCM)是猫第二常见心肌病，心内膜纤维化导致心室充盈受限。双心房显著扩大。B超可诊断。',homeCare:['控制心率和改善舒张功能','预防血栓（氯吡格雷）','利尿剂（控制心衰症状）'],forbidden:['禁止不抗凝（血栓风险）'],differential:[{disease:'HCM',differentiator:'HCM左室壁增厚；RCM以心房扩大为主+左室壁厚度正常',questions:['B超结果：室壁厚度+心房大小？']}]},
  {id:'feline-cardio-004',disease:'猫心丝虫病',species:['猫'],category:'心血管',primary:['咳嗽','呼吸急促','呕吐'],secondary:['嗜睡','体重下降','突然死亡'],urgency:'high',diagnosis:'猫心丝虫较犬罕见但更致命。猫不是理想宿主，感染虫量少（1-2条），但可引起严重炎症反应（HARD——心丝虫相关呼吸病）。抗体+抗原检测+B超可诊断。无可用的杀成虫药。',homeCare:['每月心丝虫预防药','对症支持（激素减轻炎症）','手术取虫（如有条件）'],forbidden:['禁止使用犬用杀心丝虫成虫药（对猫有毒）'],differential:[{disease:'猫哮喘',differentiator:'哮喘无心丝虫抗体/抗原阳性，支气管灌洗见嗜酸性粒细胞',questions:['有无心丝虫检测？']}]},
  {id:'feline-dig-008',disease:'猫胃淋巴瘤',species:['猫'],category:'消化系统',primary:['慢性呕吐','体重显著下降','食欲减退'],secondary:['腹泻','嗜睡'],urgency:'high',diagnosis:'猫胃肠道淋巴瘤是最常见猫肠道肿瘤，老年猫高发。分为低级别（小细胞性）和高级别（大细胞性）。肠道全层活检+免疫组化可确诊和分型。低级别淋巴瘤CHOP方案化疗效果好。',homeCare:['化疗（CHOP或苯丁酸氮芥+泼尼松龙）','营养支持','定期复查'],forbidden:['禁止不经活检就诊断（与IBD难以区分）'],differential:[{disease:'IBD',differentiator:'IBD与低级别淋巴瘤内镜+活检有时难以区分（均小细胞浸润），需免疫组化和PCR克隆性分析',questions:['有无肠道活检+免疫组化结果？']}]},
  {id:'feline-dig-009',disease:'猫巨结肠',species:['猫'],category:'消化系统',primary:['严重便秘','巨大坚硬粪块','食欲下降'],secondary:['呕吐','精神萎靡','体重下降'],urgency:'high',diagnosis:'猫巨结肠是结肠永久性扩张+蠕动丧失。常见于慢性便秘未处理。X光见结肠极度扩张。内科治疗无效者需结肠次全切除术。',homeCare:['严重者需结肠次全切除术','术后软便为正常现象（结肠切除后水分吸收减少）','终身高纤维/易消化饮食'],forbidden:['禁止对内科治疗无效者不手术','禁止术后不调整饮食'],differential:[{disease:'慢性便秘',differentiator:'慢性便秘结肠大小可逆（排便后可缩小），巨结肠为永久扩张',questions:['X光灌肠后结肠能否缩小？']}]},
  {id:'feline-dig-010',disease:'猫肝脂质沉积症(脂肪肝)严重型',species:['猫'],category:'消化系统',primary:['食欲废绝','严重黄疸','极度消瘦'],secondary:['呕吐','嗜睡','凝血功能障碍'],urgency:'critical',diagnosis:'见消化系统脂肪肝条目。此为严重型，需ICU级别治疗。强制营养支持（食道饲管/鼻饲管）至少4-6周。',homeCare:['⚠️ ICU住院','食道饲管放置（强制营养）','保肝治疗（SAMe/水飞蓟/维生素K）','止吐+胃黏膜保护','逐步恢复自主进食'],forbidden:['禁止不经饲管仅靠静脉营养','禁止过早拔除饲管（需等自主进食稳定）'],differential:[{disease:'胆管肝炎',differentiator:'胆管肝炎常伴发热和腹痛，B超见胆管扩张',questions:['B超有无胆管扩张？']}]},
  {id:'feline-derm-005',disease:'猫痤疮',species:['猫'],category:'皮肤科',primary:['下颏黑头粉刺','局部脱毛','红肿'],secondary:['继发感染（脓疱）','瘙痒'],urgency:'low',diagnosis:'猫痤疮是下颏毛囊角化异常+继发感染。可能与塑料食盆过敏、理毛不足、应激相关。严重者可形成化脓性毛囊炎和蜂窝织炎。',homeCare:['改用陶瓷/不锈钢食盆','定期清洁下颏（氯己定/过氧化苯甲酰）','严重者局部抗生素/维A酸'],forbidden:['禁止使用塑料食盆','禁止挤压粉刺'],differential:[{disease:'嗜酸性肉芽肿',differentiator:'嗜酸性肉芽肿为增生性病变，细胞学见嗜酸性粒细胞',questions:['病变是否在下颏？有无做过细胞学？']}]},
  {id:'feline-derm-006',disease:'猫耳廓皮肤病（光化性皮炎）',species:['猫'],category:'皮肤科',primary:['耳尖红肿/脱屑/结痂','耳尖卷曲'],secondary:['瘙痒','疼痛'],urgency:'medium',diagnosis:'光化性皮炎是白毛猫耳尖因长期日晒导致的皮肤损伤，可进展为鳞状细胞癌。需防晒和早期手术。',homeCare:['严格防晒（室内/防晒霜）','严重者耳尖切除术','定期检查恶变（活检）'],forbidden:['禁止让白毛猫长期暴晒'],differential:[{disease:'耳螨',differentiator:'耳螨在耳道内而非耳尖，可见咖啡渣样分泌物和虫体',questions:['病变在耳尖还是耳道内？']}]},
  {id:'feline-infect-007',disease:'猫血巴尔通体病（猫传贫）',species:['猫'],category:'传染病',primary:['贫血（牙龈苍白）','嗜睡','呼吸急促'],secondary:['发热','黄疸','脾肿大'],urgency:'high',diagnosis:'猫血巴尔通体(Mycoplasma haemofelis)寄生于红细胞表面导致溶血性贫血。经跳蚤/蜱虫叮咬或咬伤传播。血涂片见红细胞表面嗜碱性小体+PCR可确诊。',homeCare:['多西环素（4周）','严重贫血需输血','免疫抑制（激素，遵医嘱）','控制跳蚤蜱虫'],forbidden:['禁止不使用抗生素','禁止不控制外寄生虫'],differential:[{disease:'IMHA',differentiator:'IMHA库姆斯试验阳性，血涂片无红细胞表面病原体',questions:['血涂片有无红细胞表面嗜碱性小体？']}]},
  {id:'feline-infect-008',disease:'猫孢子丝菌病',species:['猫'],category:'传染病',primary:['皮肤结节/溃疡（尤其头部和四肢）','淋巴管串珠样结节'],secondary:['呼吸道症状（吸入型）','发热'],urgency:'high',diagnosis:'孢子丝菌病是申克孢子丝菌经皮肤伤口感染导致的真菌病。户外猫高发。猫可排出大量真菌→人畜共患（兽医感染风险！）。细胞学/真菌培养可确诊。',homeCare:['伊曲康唑长期治疗（数月）','严格室内饲养','处理猫时戴手套（人畜共患风险高）'],forbidden:['禁止放养','禁止不戴手套接触病变（可传染给人）'],differential:[{disease:'隐球菌病',differentiator:'隐球菌多见于鼻腔（鼻部肿胀），墨汁染色见厚荚膜酵母',questions:['病变部位？细胞学结果？']}]},
  {id:'feline-neuro-003',disease:'猫前庭综合征',species:['猫'],category:'神经系统',primary:['头倾斜','眼球震颤','共济失调'],secondary:['呕吐（晕动症）','转圈','无法站立'],urgency:'high',diagnosis:'猫前庭综合征分为外周性（中耳炎/耳息肉/特发性）和中枢性（脑干病变/FIP/肿瘤）。特发性前庭综合征常见于夏末秋初的户外幼猫。神经学检查可定位。',homeCare:['支持治疗（防摔伤）','查找原发病因（耳镜/B超/MRI）','止晕药','大多数特发性病例数周内自愈'],forbidden:['禁止不做耳镜检查就放弃','禁止不排除中耳炎/息肉'],differential:[{disease:'脑干肿瘤',differentiator:'中枢性前庭伴其他脑神经异常+意识改变，MRI可确诊',questions:['有无其他神经症状？MRI结果？']}]},
  {id:'feline-neuro-004',disease:'猫小脑发育不全',species:['猫'],category:'神经系统',primary:['意向性震颤','共济失调','步态蹒跚'],secondary:['头部震颤'],urgency:'low',diagnosis:'猫小脑发育不全是先天性疾病，母猫妊娠期感染猫瘟病毒(FPV)可导致幼猫小脑发育不全。症状非渐进性（不会恶化）。MRI见小脑体积缩小可确诊。猫生活质量通常可接受。',homeCare:['室内饲养（防摔伤）','食盆水盆固定（防打翻）','不需要药物治疗','生活质量管理'],forbidden:['禁止安乐（症状不加重，猫可适应良好）'],differential:[{disease:'溶酶体贮积症',differentiator:'贮积症症状为渐进性（逐渐加重），MRI+酶学检查可区分',questions:['症状是否渐进性加重？']}]},
  {id:'feline-uro-006',disease:'猫输尿管结石',species:['猫'],category:'泌尿系统',primary:['血尿','腹痛','精神萎靡'],secondary:['呕吐','食欲下降'],urgency:'critical',diagnosis:'猫输尿管结石多为草酸钙，可导致输尿管梗阻→肾盂积水→肾功能不可逆损伤。CT是诊断金标准。需紧急手术（输尿管切开取石/输尿管支架/SUB旁路）。',homeCare:['⚠️ 需紧急就医','手术解除梗阻','术后监测肾功能','增加饮水+泌尿道处方粮防复发'],forbidden:['禁止等待自行排出（输尿管梗阻不会自行解除）'],differential:[{disease:'肾结石',differentiator:'肾结石在肾脏内，输尿管结石已进入输尿管；B超/CT可定位',questions:['结石在肾脏还是输尿管？肾功能有无受损？']}]},
  {id:'feline-uro-007',disease:'猫肾盂肾炎',species:['猫'],category:'泌尿系统',primary:['发热','腰痛','精神萎靡'],secondary:['多饮多尿','呕吐','食欲下降'],urgency:'high',diagnosis:'肾盂肾炎是细菌上行感染至肾盂和肾实质。尿液细菌培养+药敏+B超（肾盂扩张）可诊断。需长疗程抗生素（4-6周）。',homeCare:['抗生素（根据药敏，4-6周）','增加饮水','复查尿培养确认清除','排查潜在病因（结石/解剖异常）'],forbidden:['禁止抗生素疗程不足','禁止不查找潜在病因'],differential:[{disease:'下泌尿道感染',differentiator:'下泌尿道感染无发热和腰痛，B超肾盂正常',questions:['有无发热和腰痛？']}]},
  {id:'feline-derm-007',disease:'猫皮肤肥大细胞瘤',species:['猫'],category:'皮肤科',primary:['皮肤结节（单个或多个）','瘙痒'],secondary:['红斑','脱毛'],urgency:'medium',diagnosis:'猫皮肤肥大细胞瘤较犬常见，多为良性。组织细胞型多见于年轻猫（<4岁的暹罗猫），可自行消退。肥大细胞型多见于老年猫。细针穿刺细胞学可快速诊断。手术切除可治愈。',homeCare:['手术切除（宽边缘）','组织细胞型可观察（可能自愈）','活检病理确定分型'],forbidden:['禁止不切除（少数恶性型可转移）'],differential:[{disease:'嗜酸性肉芽肿',differentiator:'嗜酸性肉芽肿细胞学见嗜酸性粒细胞而非肥大细胞',questions:['细针穿刺细胞学结果？']}]},
  {id:'feline-par-004',disease:'猫球虫病',species:['猫'],category:'寄生虫',primary:['腹泻（可能带血/黏液）','体重下降','脱水'],secondary:['呕吐','食欲下降'],urgency:'medium',diagnosis:'猫球虫(Cystoisospora felis/rivolta)是幼猫常见肠道原虫。多猫环境（救助站/猫舍）高发。粪便漂浮法镜检卵囊可确诊。',homeCare:['磺胺类药物治疗','环境彻底消毒（卵囊对环境抵抗力强）','隔离病猫','保持环境干燥'],forbidden:['禁止不处理环境（卵囊可长期存活）'],differential:[{disease:'贾第虫',differentiator:'贾第虫腹泻更臭、粪便漂浮见滋养体/包囊；球虫见卵囊',questions:['粪便镜检结果？']}]},
  {id:'feline-par-005',disease:'猫贾第虫病',species:['猫'],category:'寄生虫',primary:['慢性软便','腹泻（恶臭/油腻/浅色）','体重下降'],secondary:['被毛粗糙','食欲正常'],urgency:'medium',diagnosis:'猫贾第虫(Giardia)是肠道原虫，经粪-口传播。多猫环境高发。粪便漂浮法（硫酸锌）+ELISA抗原检测可诊断。人畜共患。',homeCare:['甲硝唑或芬苯达唑治疗','彻底环境消毒','保持环境干燥','同舍猫同时治疗'],forbidden:['禁止仅治疗一只（同舍猫都需治疗）'],differential:[{disease:'猫蛔虫',differentiator:'蛔虫可见成虫，镜检为虫卵而非原虫',questions:['粪便镜检有无原虫？ELISA？']}]},
]

function write(dir: string, list: D[]) {
  const by: Record<string, ReturnType<typeof e>[]> = {}
  for (const d of list) { const f = catMap[d.category] || d.category; if (!by[f]) by[f] = []; by[f].push(e(d)) }
  for (const [f, items] of Object.entries(by)) {
    const fp = path.join(dir, `${f}.json`)
    let exist: Array<{ id?: string }> = []
    if (fs.existsSync(fp)) { try { exist = JSON.parse(fs.readFileSync(fp,'utf-8')) as Array<{ id?: string }> } catch {} }
    const ids = new Set(exist.map((x) => x.id))
    const add = items.filter(x => !ids.has(x.id))
    if (add.length > 0) fs.writeFileSync(fp, JSON.stringify([...exist, ...add], null, 2), 'utf-8')
    console.log(`  ${f}: +${add.length} → ${exist.length + add.length}`)
  }
}

console.log('=== 犬第3批 ===')
write(path.join(BASE, 'dogs'), DOG3)
console.log(`  +${DOG3.length} 种`)
console.log('\n=== 猫第3批 ===')
write(path.join(BASE, 'cats'), CAT3)
console.log(`  +${CAT3.length} 种`)
