/**
 * Round 1: Knowledge Base Q&A Testing
 * Tests 100 common dog diseases and 100 common cat diseases against the knowledge base,
 * triage engine, normalizer, and demo mode simulation.
 */

// ---- Dog Disease Test Cases (100) ----
export const DOG_DISEASES = [
  // Digestive System (1-20)
  { name: '急性胃炎', symptoms: '狗呕吐三次，不吃东西，精神萎靡' },
  { name: '慢性胃炎', symptoms: '狗断断续续呕吐一周，食欲时好时坏' },
  { name: '急性胃肠炎', symptoms: '狗拉稀带血，呕吐，不吃不喝' },
  { name: '肠道异物', symptoms: '狗吞了一个塑料玩具，一直干呕' },
  { name: '胰腺炎', symptoms: '狗吃了肥肉后呕吐，弓着背，腹部疼痛' },
  { name: '细小病毒感染', symptoms: '小狗拉血便，腥臭味，呕吐不止，精神极差' },
  { name: '冠状病毒感染', symptoms: '幼犬拉黄色水样便，呕吐，精神差' },
  { name: '便秘', symptoms: '狗三天没拉屎，蹲着拉不出来，食欲差' },
  { name: '胃扩张扭转(GDV)', symptoms: '大狗吃完饭后肚子胀得很大，干呕，呼吸困难' },
  { name: '结肠炎', symptoms: '狗拉稀带黏液和血丝，频繁想拉但拉不多' },
  { name: '肠道寄生虫', symptoms: '狗拉稀，便里有白色虫体，体重下降' },
  { name: '食物过敏', symptoms: '狗换粮后开始拉稀，皮肤也发痒' },
  { name: '胃溃疡', symptoms: '狗吐咖啡色液体，黑便，精神萎靡' },
  { name: '肠套叠', symptoms: '狗剧烈腹痛，呕吐，拉果酱样血便' },
  { name: '巨食道症', symptoms: '狗吃完就吐未消化食物，体重下降' },
  { name: '肝炎', symptoms: '狗眼白发黄，呕吐，不吃东西，尿很黄' },
  { name: '肝硬化', symptoms: '狗腹围增大，消瘦，偶尔呕吐' },
  { name: '胆囊炎', symptoms: '狗吐黄水，右上腹疼痛，发热' },
  { name: '口炎', symptoms: '狗口臭严重，牙龈红肿，流口水，吃东西困难' },
  { name: '食管异物', symptoms: '狗突然不停吞咽动作，流口水，想吐吐不出' },

  // Urinary System (21-30)
  { name: '尿闭/下泌尿道阻塞', symptoms: '公狗频繁做排尿姿势但尿不出来，肚子胀' },
  { name: '膀胱炎', symptoms: '狗尿频尿急，尿中带血，排尿疼痛' },
  { name: '膀胱结石', symptoms: '狗尿血，排尿困难，尿流变细' },
  { name: '肾衰竭(急性)', symptoms: '狗突然不排尿，呕吐，口臭，精神极差' },
  { name: '肾衰竭(慢性)', symptoms: '老年狗多饮多尿，消瘦，口臭，食欲差' },
  { name: '尿路感染', symptoms: '狗频繁舔生殖器，尿频，尿液浑浊有异味' },
  { name: '前列腺疾病', symptoms: '未绝育公狗排尿困难，大便变细，后腿无力' },
  { name: '肾结石', symptoms: '狗尿血，腰部疼痛，精神萎靡' },
  { name: '尿道炎', symptoms: '狗排尿时惨叫，尿道口红' },
  { name: '糖尿病', symptoms: '狗多饮多尿，吃得多但越来越瘦' },

  // Respiratory System (31-40)
  { name: '犬窝咳', symptoms: '狗干咳像卡了东西，尤其夜间和运动后加重' },
  { name: '肺炎', symptoms: '狗咳嗽，发热40度，呼吸困难，精神萎靡' },
  { name: '支气管炎', symptoms: '狗持续咳嗽，有痰音，运动后喘' },
  { name: '鼻炎', symptoms: '狗打喷嚏，流清鼻涕，鼻子不通气' },
  { name: '气管塌陷', symptoms: '小型犬激动时发出鹅叫声，呼吸困难' },
  { name: '肺水肿', symptoms: '狗突然呼吸困难，咳粉红色泡沫，无法躺下' },
  { name: '脓胸', symptoms: '狗呼吸困难，发热，精神极差，牙龈苍白' },
  { name: '上呼吸道感染', symptoms: '狗咳嗽打喷嚏流鼻涕，眼睛有分泌物' },
  { name: '鼻腔异物', symptoms: '狗不停打喷嚏，用爪子抓鼻子，一侧鼻孔流脓' },
  { name: '喉炎', symptoms: '狗叫声变哑，干咳，吞咽困难' },

  // Skin & Ear (41-55)
  { name: '过敏性皮炎', symptoms: '狗全身发痒，不停抓挠，皮肤发红有疹子' },
  { name: '真菌感染(癣)', symptoms: '狗身上出现圆形脱毛斑，有皮屑，瘙痒' },
  { name: '蠕形螨', symptoms: '狗局部脱毛，皮肤发红但不怎么痒' },
  { name: '疥螨', symptoms: '狗剧烈瘙痒，耳尖和肘部脱毛结痂' },
  { name: '外耳炎', symptoms: '狗不停挠耳朵甩头，耳朵发臭有褐色分泌物' },
  { name: '中耳炎', symptoms: '狗歪头，走路不稳，耳朵疼痛' },
  { name: '耳螨', symptoms: '狗耳朵里有黑色咖啡渣样分泌物，剧烈瘙痒' },
  { name: '湿疹', symptoms: '狗皮肤潮湿发红，有渗出液，瘙痒' },
  { name: '趾间炎', symptoms: '狗不停舔脚，趾间红肿有脓' },
  { name: '脂溢性皮炎', symptoms: '狗皮肤油腻有大量皮屑，有异味' },
  { name: '脓皮症', symptoms: '狗皮肤出现脓疱，结痂，脱毛' },
  { name: '跳蚤过敏性皮炎', symptoms: '狗腰背部剧烈瘙痒，有小黑点（跳蚤粪便）' },
  { name: '马拉色菌皮炎', symptoms: '狗皮肤油腻发臭，爪子脖子腋下红肿' },
  { name: '皮肤肿瘤', symptoms: '狗身上长了一个不断增大的肿块，表面破溃' },
  { name: '肛周腺瘤', symptoms: '狗肛门周围长了多个小疙瘩，排便困难' },

  // Eye (56-65)
  { name: '结膜炎', symptoms: '狗眼睛红肿，流泪多，眼屎增多' },
  { name: '角膜炎', symptoms: '狗眼睛表面浑浊，眯眼怕光，流泪' },
  { name: '干眼症', symptoms: '狗眼睛有黏稠分泌物，角膜干燥无光泽' },
  { name: '青光眼', symptoms: '狗眼睛胀大突出，眼压高，疼痛明显' },
  { name: '白内障', symptoms: '老年狗眼睛晶状体变白浑浊，视力下降' },
  { name: '樱桃眼(第三眼睑脱出)', symptoms: '狗眼角有一个红色肉球突出' },
  { name: '泪道阻塞', symptoms: '狗眼下长期有泪痕，眼周毛发湿润' },
  { name: '角膜溃疡', symptoms: '狗眯眼流泪，角膜上有白色凹陷' },
  { name: '葡萄膜炎', symptoms: '狗眼睛发红疼痛，瞳孔缩小，怕光' },
  { name: '眼睑内翻', symptoms: '狗眼睫毛往里长刺激眼球，不停流泪眯眼' },

  // Orthopedic & Neurological (66-80)
  { name: '髋关节发育不良', symptoms: '大狗后腿跛行，起身困难，不愿意跑跳' },
  { name: '髌骨脱位', symptoms: '小狗走着走着突然抬一条后腿跳几步' },
  { name: '前十字韧带断裂', symptoms: '狗突然一条后腿不敢着地，关节肿胀' },
  { name: '关节炎', symptoms: '老年狗走路僵硬，尤其早上刚起来时明显' },
  { name: '椎间盘疾病(IVDD)', symptoms: '腊肠狗突然后腿瘫痪，腰部疼痛，无法行走' },
  { name: '骨折', symptoms: '狗被车撞后腿变形，不敢着地，剧烈疼痛' },
  { name: '癫痫', symptoms: '狗突然倒地抽搐，口吐白沫，四肢僵直' },
  { name: '前庭综合征', symptoms: '老年狗突然歪头，眼球震颤，走路转圈，站不稳' },
  { name: '脑炎', symptoms: '狗抽搐，行为异常，转圈，意识模糊' },
  { name: '重症肌无力', symptoms: '狗活动后越来越无力，休息后好转' },
  { name: '颈椎病', symptoms: '狗脖子僵硬疼痛，不敢低头吃饭，前腿跛行' },
  { name: '骨肉瘤', symptoms: '大狗一条腿持续性跛行，局部肿胀发热' },
  { name: '肘关节发育不良', symptoms: '年轻大狗前腿跛行，肘关节肿胀' },
  { name: '脊髓炎', symptoms: '狗突然后肢无力，逐渐发展到前肢' },
  { name: '运动不耐受', symptoms: '狗走几步就喘，趴下不愿动' },

  // Cardiovascular & Blood (81-90)
  { name: '心丝虫病', symptoms: '狗咳嗽，运动耐力下降，腹围增大，牙龈发紫' },
  { name: '扩张型心肌病', symptoms: '大型犬活动后昏倒，腹围增大，呼吸困难' },
  { name: '二尖瓣关闭不全', symptoms: '小型老年犬咳嗽，尤其夜间加重，运动后喘' },
  { name: '贫血', symptoms: '狗牙龈苍白，虚弱无力，呼吸急促' },
  { name: '血小板减少症', symptoms: '狗皮肤出现瘀点瘀斑，牙龈出血' },
  { name: '弥散性血管内凝血(DIC)', symptoms: '狗多处出血不止，瘀斑，精神极差' },
  { name: '心包积液', symptoms: '狗腹围突然增大，呼吸困难，牙龈发紫，虚弱' },
  { name: '高血压', symptoms: '老年狗突然失明，眼底出血，鼻子出血' },
  { name: '溶血性贫血', symptoms: '狗尿呈酱油色，眼白发黄，虚弱无力' },
  { name: '淋巴瘤', symptoms: '狗全身淋巴结肿大，消瘦，发热，食欲差' },

  // Endocrine & Metabolic (91-100)
  { name: '库欣综合征', symptoms: '狗多饮多尿，肚子大，皮肤薄，对称性脱毛' },
  { name: '甲状腺功能减退', symptoms: '狗精神差，肥胖，脱毛，皮肤干燥，怕冷' },
  { name: '糖尿病酮症酸中毒', symptoms: '狗精神极差，呕吐，呼吸有烂苹果味' },
  { name: '低血糖', symptoms: '小狗突然虚弱，抽搐，意识模糊' },
  { name: '肥胖症', symptoms: '狗体重严重超标，活动少，喘气，关节负担大' },
  { name: '电解质紊乱', symptoms: '狗呕吐腹泻后虚弱，肌肉颤抖，心律不齐' },
  { name: '维生素A中毒', symptoms: '狗长期吃肝脏后关节僵硬，骨骼异常' },
  { name: '钙磷代谢紊乱', symptoms: '狗抽搐，肌肉震颤，走路僵硬' },
  { name: '肾上腺皮质功能减退', symptoms: '狗反复呕吐腹泻，精神差，心率慢，虚弱' },
  { name: '甲状旁腺功能亢进', symptoms: '狗多饮多尿，肌肉无力，骨骼疼痛' },
];

// ---- Cat Disease Test Cases (100) ----
export const CAT_DISEASES = [
  // Digestive System (1-20)
  { name: '急性胃炎', symptoms: '猫吐了两次，不吃猫粮，躲在角落不出来' },
  { name: '毛球症', symptoms: '猫干呕，吐出毛球，食欲下降' },
  { name: '慢性胃炎', symptoms: '猫间歇性呕吐一个月，食欲减退，消瘦' },
  { name: '肠道异物(线性异物)', symptoms: '猫玩线后吐线头出来，食欲废绝，腹痛' },
  { name: '便秘/巨结肠', symptoms: '猫三天不拉，蹲猫砂盆拉不出，食欲差' },
  { name: '胰腺炎', symptoms: '猫不吃不喝，呕吐，精神极差，腹部触诊疼痛' },
  { name: '猫瘟(泛白细胞减少症)', symptoms: '幼猫高热41度，剧烈呕吐，拉血便，精神极差' },
  { name: '肝炎/肝脂变', symptoms: '胖猫突然不吃东西一周，眼白变黄，呕吐' },
  { name: '炎性肠病(IBD)', symptoms: '猫慢性间歇性腹泻，体重下降，偶尔呕吐' },
  { name: '口腔炎', symptoms: '猫口臭，流口水，牙龈红肿溃烂，吃东西惨叫' },
  { name: '食物过敏', symptoms: '猫换粮后全身发痒，拉稀，频繁抓挠' },
  { name: '肠道寄生虫', symptoms: '猫拉稀，便里看到白色米粒样虫体，屁股蹭地' },
  { name: '胃溃疡', symptoms: '猫吐咖啡色液体，黑便，食欲废绝' },
  { name: '肠梗阻', symptoms: '猫突然剧烈呕吐，腹痛，不排便不排气' },
  { name: '食管炎', symptoms: '猫吞咽困难，流口水，反流未消化食物' },
  { name: '胆管肝炎', symptoms: '猫反复发热，黄疸，呕吐，食欲差' },
  { name: '腹泻综合征', symptoms: '幼猫水样腹泻，脱水，精神萎靡' },
  { name: '毛球性肠梗阻', symptoms: '猫几天不排便，呕吐，腹部触诊有硬块' },
  { name: '消化不良', symptoms: '猫吃多了后呕吐未消化食物，精神正常' },
  { name: '肝硬化', symptoms: '老年猫腹水，消瘦，黄疸，精神差' },

  // Urinary System (21-35)
  { name: 'FLUTD/尿闭', symptoms: '公猫频繁进猫砂盆蹲半天没尿出来，惨叫' },
  { name: '特发性膀胱炎(FIC)', symptoms: '猫尿频，尿中带血，在沙发上乱尿，精神紧张' },
  { name: '膀胱结石', symptoms: '猫尿血，排尿困难，频繁舔生殖器' },
  { name: '肾衰竭(急性)', symptoms: '猫接触百合花后突然不排尿，呕吐，精神极差' },
  { name: '肾衰竭(慢性)', symptoms: '老年猫多饮多尿，口臭，口腔溃疡，消瘦' },
  { name: '尿路感染', symptoms: '母猫尿频尿急，尿液浑浊有臭味，舔生殖器' },
  { name: '尿道栓子', symptoms: '公猫突然无法排尿，惨叫，腹部胀大' },
  { name: '肾结石', symptoms: '猫尿血，腰部疼痛，不愿被抱' },
  { name: '多囊肾', symptoms: '波斯猫体检发现肾脏多个囊肿，逐渐肾功能下降' },
  { name: '输尿管结石', symptoms: '猫剧烈腹痛，尿血，呕吐，精神极差' },
  { name: '膀胱肿瘤', symptoms: '老年猫持续尿血，排尿困难，体重下降' },
  { name: '尿道狭窄', symptoms: '猫排尿时间很长，尿流细，反复尿路感染' },
  { name: '尿失禁', symptoms: '猫睡觉时漏尿，会阴部潮湿' },
  { name: '间质性膀胱炎', symptoms: '猫反复出现血尿和乱尿，压力大时加重' },
  { name: '肾盂肾炎', symptoms: '猫发热，腰背部疼痛，尿浑浊，精神萎靡' },

  // Respiratory System (36-45)
  { name: '猫鼻支(疱疹病毒)', symptoms: '猫打喷嚏，流眼泪，眼鼻分泌物多，发热不吃' },
  { name: '猫杯状病毒', symptoms: '猫口腔溃疡，流口水，打喷嚏，发热' },
  { name: '猫衣原体感染', symptoms: '猫结膜炎严重，眼睛红肿，大量眼分泌物' },
  { name: '猫哮喘', symptoms: '猫阵发性咳嗽，呼吸急促，像喘不过气' },
  { name: '肺炎', symptoms: '猫呼吸困难，发热40度，精神萎靡，不吃东西' },
  { name: '支气管炎', symptoms: '猫慢性咳嗽，有痰，运动后加重' },
  { name: '鼻炎/鼻窦炎', symptoms: '猫长期打喷嚏，流黄鼻涕，鼻子堵塞' },
  { name: '胸腔积液', symptoms: '猫呼吸困难，腹式呼吸，牙龈发紫' },
  { name: '乳糜胸', symptoms: '猫呼吸越来越困难，X光见胸腔积液' },
  { name: '鼻腔肿瘤', symptoms: '老年猫一侧鼻孔反复流血，面部肿胀' },

  // Skin & Ear (46-60)
  { name: '猫癣(真菌感染)', symptoms: '猫耳朵边缘和面部出现圆形脱毛，有皮屑结痂' },
  { name: '过敏性皮炎', symptoms: '猫全身瘙痒，不停舔毛，肚子和大腿内侧脱毛' },
  { name: '耳螨', symptoms: '猫不停挠耳朵甩头，耳朵里有黑色咖啡渣样分泌物' },
  { name: '外耳炎', symptoms: '猫耳朵发红发臭，有黄色分泌物，不让碰耳朵' },
  { name: '蠕形螨', symptoms: '猫局部脱毛，皮肤发红，有黑色粉刺样物' },
  { name: '粟粒性皮炎', symptoms: '猫全身出现小颗粒状丘疹和结痂，剧烈瘙痒' },
  { name: '嗜酸性肉芽肿', symptoms: '猫嘴唇或下巴出现红肿隆起的溃疡性病变' },
  { name: '跳蚤过敏性皮炎', symptoms: '猫背部和尾巴根部剧烈瘙痒，有小黑点' },
  { name: '精神性脱毛', symptoms: '猫过度舔毛导致腹部和腿内侧毛发稀少' },
  { name: '马拉色菌皮炎', symptoms: '猫皮肤油腻发黑，有异味，指甲缝发黑' },
  { name: '猫痤疮', symptoms: '猫下巴出现黑头粉刺，红肿，有时化脓' },
  { name: '肛周瘘', symptoms: '猫肛门周围有瘘管和溃烂，排便困难疼痛' },
  { name: '皮肤鳞状细胞癌', symptoms: '白猫耳朵尖出现不愈合的溃烂，逐渐扩大' },
  { name: '天疱疮', symptoms: '猫面部和足垫出现水疱和溃烂，精神差发热' },
  { name: '日光性皮炎', symptoms: '白猫耳朵和鼻子皮肤发红脱皮，夏季加重' },

  // Eye (61-70)
  { name: '结膜炎', symptoms: '猫眼睛红肿，流泪多，眼屎黏稠' },
  { name: '角膜炎/角膜溃疡', symptoms: '猫眯眼怕光流泪，角膜上有白色浑浊区' },
  { name: '猫疱疹病毒性眼病', symptoms: '幼猫眼睛严重红肿，角膜溃疡，眼鼻分泌物多' },
  { name: '青光眼', symptoms: '猫眼睛胀大，角膜浑浊，疼痛不愿睁眼' },
  { name: '白内障', symptoms: '老年猫眼睛晶状体变白，视力明显下降' },
  { name: '葡萄膜炎', symptoms: '猫眼睛发红，瞳孔缩小，前房浑浊' },
  { name: '眼睑内翻', symptoms: '猫眼睫毛往里长，不停流泪，角膜刺激' },
  { name: '泪溢症', symptoms: '猫眼下长期湿漉漉的，有褐色泪痕' },
  { name: '视网膜脱落', symptoms: '猫突然失明，瞳孔散大无反应' },
  { name: '眼前房积血', symptoms: '猫外伤后眼睛前房充满血液' },

  // Endocrine & Metabolic (71-80)
  { name: '猫糖尿病', symptoms: '猫多饮多尿，吃得多但越来越瘦，后腿无力' },
  { name: '猫甲状腺功能亢进', symptoms: '老年猫吃得多但狂瘦，多动不安，乱叫，呕吐' },
  { name: '猫肾上腺皮质功能亢进', symptoms: '猫皮肤极薄易破，肚子大，多饮多尿' },
  { name: '低血糖', symptoms: '小猫突然虚弱瘫软，抽搐，体温低' },
  { name: '肥胖症', symptoms: '猫体重严重超标，不爱动，呼吸粗重' },
  { name: '肝脂变', symptoms: '胖猫突然禁食后不吃不喝，黄疸，精神极差' },
  { name: '低钙血症', symptoms: '哺乳母猫突然抽搐，四肢僵直，发热' },
  { name: '牛磺酸缺乏', symptoms: '猫心肌无力，视力下降，繁殖障碍' },
  { name: '维生素B1缺乏', symptoms: '猫头歪，瞳孔散大，走路不稳，抽搐' },
  { name: '电解质紊乱', symptoms: '猫呕吐腹泻后虚弱无力，肌肉抽搐' },

  // Orthopedic & Neurological (81-90)
  { name: '骨折', symptoms: '猫坠楼后一条腿变形，不敢着地，惨叫' },
  { name: '骨盆骨折', symptoms: '猫被车撞后后肢瘫痪，排便排尿困难' },
  { name: '关节炎', symptoms: '老年猫走路僵硬，不愿意跳高，起床困难' },
  { name: '髋关节发育不良', symptoms: '大型猫后腿跛行，不愿活动' },
  { name: '椎间盘疾病', symptoms: '猫突然后腿拖行，大小便失禁' },
  { name: '癫痫', symptoms: '猫突然倒地抽搐，口吐白沫，意识丧失' },
  { name: '前庭疾病', symptoms: '猫突然歪头，眼球震颤，站不稳转圈' },
  { name: '脑膜炎', symptoms: '猫高热，颈项强直，抽搐，意识障碍' },
  { name: '脊髓损伤', symptoms: '猫坠落后四肢瘫痪，呼吸困难' },
  { name: '神经性疼痛', symptoms: '猫被触摸时尖叫，皮肤抽搐，过度舔咬' },

  // Infectious & Parasitic (91-100)
  { name: '猫艾滋病(FIV)', symptoms: '流浪猫反复感染，口腔炎，消瘦，发热' },
  { name: '猫白血病(FeLV)', symptoms: '猫贫血，反复发热，口腔问题，体重下降' },
  { name: '猫传染性腹膜炎(FIP)', symptoms: '幼猫腹围逐渐增大，发热不退，消瘦，眼炎' },
  { name: '弓形虫病', symptoms: '猫发热，食欲不振，呼吸困难，眼部炎症' },
  { name: '猫蛔虫感染', symptoms: '幼猫肚子大，消瘦，呕吐出虫子，拉稀' },
  { name: '猫绦虫感染', symptoms: '猫肛门周围有米粒样白色节片，屁股蹭地' },
  { name: '钩虫感染', symptoms: '猫贫血，黑便，消瘦，虚弱' },
  { name: '心丝虫病', symptoms: '猫咳嗽，呼吸困难，突然死亡' },
  { name: '猫巴尔通体病', symptoms: '猫发热，淋巴结肿大，口腔牙龈炎' },
  { name: '猫隐球菌病', symptoms: '猫鼻腔有肉芽肿，打喷嚏流脓涕，面部肿胀' },
];

// Export combined test data
export const ALL_TESTS = [
  { species: '犬', cases: DOG_DISEASES },
  { species: '猫', cases: CAT_DISEASES },
];
